### ISSUE TITLE
Lỗi validate

### ISSUE THREAD

**Issue by vanthao03596** [datnq/Vietnamese-mobile-carrier#3]
Mình thử nhập 0397962050 và test thì không được, không qua được dòng
` if (!preg_match('/^0[0-9]{8}$/', $number)) return false;`

Có thử chuyển thành '/^0[0-9]{9}$/' thì được.

**Comment by hanvanhuy1991** [comment]
> Mình thử nhập 0397962050 và test thì không được, không qua được dòng
> ` if (!preg_match('/^0[0-9]{8}$/', $number)) return false;`
> 
> Có thử chuyển thành '/^0[0-9]{9}$/' thì được.

Uh. hihi

**Comment by joeynq** [comment]
@vanthao03596 bạn có thể fix lỗi rồi tạo PR giúp tôi không?
`/^0[0-9]{9,10}$/` cho cả case 11 số cũ

**Comment by joeynq** [comment]
closed as #4
